CREATE TABLE `course_modules` (
  `coursemoduleid` bigint(10) NOT NULL AUTO_INCREMENT,
  `courseid` bigint(10) NOT NULL DEFAULT '0',
  `moduleid` bigint(10) NOT NULL DEFAULT '0',
  `instance` bigint(10) NOT NULL DEFAULT '0',
  `section` bigint(10) NOT NULL DEFAULT '0',
  `idnumber` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `addedon` bigint(10) NOT NULL DEFAULT '0',
  `score` smallint(4) NOT NULL DEFAULT '0',
  `indent` mediumint(5) NOT NULL DEFAULT '0',
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `completion` tinyint(1) NOT NULL DEFAULT '0',
  `companyid` bigint(10) NOT NULL,
  PRIMARY KEY (`coursemoduleid`),
  KEY `courmodu_status_ix` (`status`),
  KEY `courmodu_cou_ix` (`courseid`),
  KEY `courmodu_mod_ix` (`moduleid`),
  KEY `courmodu_ins_ix` (`instance`),
  KEY `courmodu_idncou_ix` (`idnumber`,`courseid`),
  KEY `fk_course_mod_company` (`companyid`),
  CONSTRAINT `fk_course_mod_company` FOREIGN KEY (`companyid`) REFERENCES `company` (`companyid`),
  CONSTRAINT `fk_course_module` FOREIGN KEY (`moduleid`) REFERENCES `modules` (`moduleid`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_course_module_course` FOREIGN KEY (`courseid`) REFERENCES `course` (`courseid`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;