CREATE TABLE `course` (
  `courseid` bigint(10) NOT NULL AUTO_INCREMENT,
  `categoryid` bigint(10) NOT NULL DEFAULT '0',
  `sortorder` bigint(10) NOT NULL DEFAULT '0',
  `fullname` varchar(254) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `shortname` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `coursenumber` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `summary` longtext COLLATE utf8_unicode_ci,
  `summaryformat` tinyint(2) NOT NULL DEFAULT '0',
  `format` varchar(21) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'topics',
  `showgrades` tinyint(2) NOT NULL DEFAULT '1',
  `startdate` bigint(10) NOT NULL DEFAULT '0',
  `enddate` bigint(10) NOT NULL DEFAULT '0',
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `createdtime` bigint(10) NOT NULL DEFAULT '0',
  `modifiedtime` bigint(10) NOT NULL DEFAULT '0',
  `enablecompletion` tinyint(1) NOT NULL DEFAULT '0',
  `completionnotify` tinyint(1) NOT NULL DEFAULT '0',
  `publishstatus` int(10) NOT NULL DEFAULT '1',
  `companyid` bigint(10) NOT NULL,
  PRIMARY KEY (`courseid`),
  KEY `cour_cat_ix` (`categoryid`),
  KEY `cour_cournum_ix` (`coursenumber`),
  KEY `cour_sho_ix` (`shortname`),
  KEY `cour_sor_ix` (`sortorder`),
  KEY `fk_course_company` (`companyid`),
  CONSTRAINT `fk_course_category` FOREIGN KEY (`categoryid`) REFERENCES `course_categories` (`categoryid`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_course_company` FOREIGN KEY (`companyid`) REFERENCES `company` (`companyid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Main course table';