// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.edumosphere.lms.domain;

import com.edumosphere.lms.domain.Company;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Company_Roo_Configurable {
    
    declare @type: Company: @Configurable;
    
}
